<template>
    <div>
        <h4>DEX</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Hendrerit dolor magna eget est lorem ipsum dolor sit. At augue eget arcu dictum varius. In metus vulputate eu scelerisque felis imperdiet proin fermentum. Augue lacus viverra vitae congue eu consequat ac felis. Ultricies leo integer malesuada nunc vel risus commodo viverra maecenas. Sed viverra ipsum nunc aliquet bibendum enim facilisis. Turpis cursus in hac habitasse platea dictumst quisque. Viverra nibh cras pulvinar mattis. Pharetra diam sit amet nisl suscipit adipiscing bibendum est ultricies. Adipiscing enim eu turpis egestas pretium aenean.</p>
        <p>Faucibus purus in massa tempor nec feugiat nisl pretium. Feugiat nisl pretium fusce id velit ut tortor pretium. Amet dictum sit amet justo donec enim. Sed faucibus turpis in eu mi. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt. Elementum tempus egestas sed sed risus. Sed risus ultricies tristique nulla aliquet. Semper eget duis at tellus at urna condimentum. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Purus faucibus ornare suspendisse sed. Hendrerit dolor magna eget est lorem ipsum dolor sit amet. Sit amet mattis vulputate enim nulla aliquet porttitor. Purus viverra accumsan in nisl nisi scelerisque eu ultrices. Neque convallis a cras semper. Quam pellentesque nec nam aliquam sem.</p>
        <p>Commodo elit at imperdiet dui accumsan sit amet nulla facilisi. Nulla posuere sollicitudin aliquam ultrices sagittis orci a. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Nam aliquam sem et tortor consequat. Id neque aliquam vestibulum morbi blandit cursus risus at. Lacus vel facilisis volutpat est velit egestas dui id. Nunc consequat interdum varius sit amet. In eu mi bibendum neque egestas congue quisque egestas. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Viverra maecenas accumsan lacus vel. Porta lorem mollis aliquam ut porttitor. Convallis posuere morbi leo urna molestie at elementum eu facilisis. Non diam phasellus vestibulum lorem sed risus ultricies tristique. Senectus et netus et malesuada. Eu feugiat pretium nibh ipsum consequat. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Amet facilisis magna etiam tempor orci eu lobortis.</p>
        <p>Ultricies lacus sed turpis tincidunt. Ultricies leo integer malesuada nunc vel risus commodo viverra. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce. Sollicitudin tempor id eu nisl nunc mi ipsum faucibus. Turpis tincidunt id aliquet risus. Nulla porttitor massa id neque aliquam. Sit amet tellus cras adipiscing enim. Quis auctor elit sed vulputate mi sit amet. Duis tristique sollicitudin nibh sit amet. Metus dictum at tempor commodo.</p>
        <p>Massa tempor nec feugiat nisl pretium fusce id velit. Sem nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. In egestas erat imperdiet sed. Euismod lacinia at quis risus sed. Dictumst quisque sagittis purus sit amet. Viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat. Est velit egestas dui id ornare arcu odio ut sem. Viverra adipiscing at in tellus integer feugiat scelerisque. Facilisis magna etiam tempor orci eu lobortis. Faucibus a pellentesque sit amet porttitor.</p>
        <p>Libero justo laoreet sit amet. A condimentum vitae sapien pellentesque habitant morbi. Quis viverra nibh cras pulvinar mattis nunc sed blandit. Maecenas ultricies mi eget mauris pharetra et ultrices. Sed enim ut sem viverra aliquet. Molestie at elementum eu facilisis. Aenean sed adipiscing diam donec adipiscing tristique risus nec feugiat. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Cursus turpis massa tincidunt dui. Accumsan sit amet nulla facilisi. Mi ipsum faucibus vitae aliquet nec ullamcorper. Morbi tincidunt ornare massa eget egestas purus.</p>
        <p>Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Donec adipiscing tristique risus nec feugiat in fermentum posuere. At tellus at urna condimentum mattis pellentesque. Erat nam at lectus urna. Egestas sed sed risus pretium quam. Non quam lacus suspendisse faucibus. Mauris ultrices eros in cursus turpis massa tincidunt. Praesent elementum facilisis leo vel fringilla est. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Id diam maecenas ultricies mi eget. Sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae. Lectus quam id leo in.</p>
    </div>
</template>